baseURL = "https://thwanisithole.co.za/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Thwani Sithole"
theme = "hermit"
enableEmoji = true
googleAnalytics = "G-LD06J0QZFE"

[author]
name = "Thwani Sithole"

[blackfriday]

[taxonomies]
tag = "tags"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
description = "thwanisithole.co.za | Thwani Sithole's personal website"

themeColor = "#494f5c"
homeSubtitle = "I'm a full stack software developer from Durban, South Africa"


justifyContent = false
relatedPosts = true
code_copy_button = true

[markup.goldmark.renderer]
unsafe = true

[[params.social]]
name = "twitter"
url = "https://twitter.com/thwani_sithole"

[[params.social]]
name = "github"
url = "https://github.com/Thwani47"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/thwani-sithole-101553a5/"

[menu]

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

# [[menu.main]]
# name = "Projects"
# url = "projects/"
# weight = 20

[[menu.main]]
name = "About"
url = "about/"
weight = 20
